<!--Write some here-->
        </div>
    </div>
</center>
    <div id="copyright" style="margin-top: 20px; font-size: 10px; text-align: center; color: #DDD; cursor: pointer">
        Designed for Embria School 2012
    </div>
    <script type="text/javascript">
        $('#copyright').hover(
            function(){
                $('#copyright').stop().animate({'color':'black'})
            },
            function(){
                $('#copyright').stop().animate({'color':'#DDD'})
            }
        ).click(function(){
                window.location = "http://embria.ru";
            });
    </script>
</body>
</html>